//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int cartId { get; set; }
        public int productId { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
