//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoiceId { get; set; }
        public Nullable<int> cartId { get; set; }
        public Nullable<System.DateTime> dateOfPayment { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<int> methodId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Method Method { get; set; }
    }
}
